const clientesData = [
  {
    id: 0,
    name: "Elton Braz",
    registered: "2018/01/01",
    role: "Guest",
    status: "Pending",
    email: "elton.braz@hotmail.com",
    msisdn: "5521994309366",
    grupo: "Amigos da DES Tecnologia",
    rua: "Senador Vergueiro",
    numeroRua: "10",
    bairro: "Flamengo",
    cidade: "Rio de Janeiro",
    estado: "RJ",
    pais: "Brasil"
  },
  {
    id: 1,
    name: "Silaz Muniz",
    registered: "2018/01/01",
    role: "Member",
    status: "Active",
    email: "silas@yahoo.com.br",
    msisdn: "5521988010001",
    grupo: "Amigos da DES Tecnologia",
    rua: "Portela",
    numeroRua: "10",
    bairro: "Olaria",
    cidade: "Rio de Janeiro",
    estado: "RJ",
    pais: "Brasil"
  },
  {
    id: 2,
    name: "Dlaivison",
    registered: "2018/02/01",
    role: "Staff",
    status: "Banned",
    email: "dlaivison@hotmail.com",
    msisdn: "5531988810976",
    grupo: "Amigos da DES Tecnologia",
    rua: "Cruzeiro",
    numeroRua: "10",
    bairro: "Atletico",
    cidade: "Belo Horizonte",
    estado: "MG",
    pais: "Brasil"
  },
  {
    id: 3,
    name: "Chetan Mohamed",
    registered: "2018/02/01",
    role: "Admin",
    status: "Inactive",
    email: "example@example.com",
    msisdn: "1345678456",
    grupo: "Contatos Ficticios",
    rua: "Marte",
    numeroRua: "10",
    bairro: "Saturno",
    cidade: "Solar",
    estado: "Sistema",
    pais: "Galaxia"
  },
  {
    id: 4,
    name: "Derick Maximinus",
    registered: "2018/03/01",
    role: "Member",
    status: "Pending",
    email: "example2@hotmail.com",
    msisdn: "23214124344",
    grupo: "Contatos Ficticios",
    rua: "Polar",
    numeroRua: "10",
    bairro: "Artico",
    cidade: "Nasa",
    estado: "PA",
    pais: "Brasil"
  },
  {
    id: 5,
    name: "Iron Man",
    registered: "2018/03/01",
    role: "Member",
    status: "Pending",
    email: "ironman@hotmail.com",
    msisdn: "23214124344",
    grupo: "Marvel",
    rua: "Polar",
    numeroRua: "10",
    bairro: "Artico",
    cidade: "Nasa",
    estado: "PA",
    pais: "Brasil"
  },
  {
    id: 6,
    name: "Capita Marvel",
    registered: "2018/03/01",
    role: "Member",
    status: "Pending",
    email: "example2@hotmail.com",
    msisdn: "23214124344",
    grupo: "Marvel",
    rua: "Polar",
    numeroRua: "10",
    bairro: "Artico",
    cidade: "Nasa",
    estado: "PA",
    pais: "Brasil"
  },
  {
    id: 7,
    name: "Hulk",
    registered: "2018/03/01",
    role: "Member",
    status: "Pending",
    email: "hulk@hotmail.com",
    msisdn: "23214124344",
    grupo: "Marvel",
    rua: "Polar",
    numeroRua: "10",
    bairro: "Artico",
    cidade: "Nasa",
    estado: "PA",
    pais: "Brasil"
  }
];

export default clientesData;
